name: Actionslaw Trigger Action
description: Action to trigger Actionslaw workflows
branding:
  icon: settings
  color: white
inputs:
  on:
    description: Configuration for Actionslaw trigger
    required: true
outputs:
  items:
    description: Array of workflow items to process
    value: ${{ steps.actionslaw.outputs.items }}
runs:
  using: composite
  steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v3
    - run: npm ci
      shell: bash
    - id: actionslaw
      run: npm run start
      shell: bash
